update `run_tests` to work with purposefullly failing tests

diff --git a/e2e/install_apps b/e2e/install_apps
--- a/e2e/install_apps
+++ b/e2e/install_apps
@@ -17,9 +17,9 @@ for file in ./apps/*; do
 
 	extension="${file##*.}"
 	if [ "$extension" = "apk" ]; then
-		adb install -r "$file" >/dev/null
+		adb install -r "$file" >/dev/null || echo "adb: could not install $filename"
 	elif [ "$extension" = "app" ] && [ "$(uname)" = "Darwin" ]; then
-		xcrun simctl install booted "$file"
+		xcrun simctl install booted "$file" || echo "xcrun: could not install $filename"
 	else
 		echo "unknown file extension $extension"
 	fi
