trigger example failure

diff --git a/e2e/run_tests b/e2e/run_tests
--- a/e2e/run_tests
+++ b/e2e/run_tests
@@ -8,12 +8,18 @@ command -v maestro >/dev/null 2>&1 || { echo "maestro is required" && exit 1; }
 
 selected_app="${1:-}"
 
+FAILED=false
 for file in ./flows/*; do
 	filename="$(basename "$file")"
 
 	if [ -z "$selected_app" ] || [ "$selected_app" = "$filename" ]; then
 		cd "$file" || exit 1
-		maestro --device emulator-5554 test . # --format junit
+		maestro --device emulator-5554 test . || FAILED=true
 		cd - >/dev/null || exit 1
 	fi
 done
+
+if [ "$FAILED" = true ]; then
+  echo "Some tests failed"
+  exit 1
+fi
